title: Priya # your name (or website title) here
logo: "Priya pic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A passionate Machine Learning enthusiast finding patterns in data for solving business & community challenges  
  <br><br>
  
  <a href="https://www.linkedin.com/in/example/">LinkedIn</a> 
  

