title: Priya # your name (or website title) here
logo: "Priya pic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  A passionate Machine Learning enthusiast using patterns in data to find solutions for business & community challenges 
  <br><br>
  
  <a href="https://www.linkedin.com/in/sathyapriya-subramaniam-327349216/>LinkedIn</a> 
  
  [LinkedIn](https://www.linkedin.com/in/sathyapriya-subramaniam-327349216/)
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
